name: attraction_workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['lint', 'build', 'type']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Run commands
        run: pnpm ${{ matrix.command }}
        env:
          MOCK_URL: ${{ secrets.MOCK_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
          NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET }}
          NEXT_PUBLIC_FE_URL: ${{ secrets.NEXT_PUBLIC_FE_URL }}
          NEXT_PUBLIC_OAUTH_URL: ${{ secrets.NEXT_PUBLIC_OAUTH_URL }}
          NEXT_PUBLIC_S3_BUCKET_URL: ${{ secrets.NEXT_PUBLIC_S3_BUCKET_URL }}
          NEXT_PUBLIC_S3_IMAGE_UPLOAD_BUCKET_NAME: ${{ secrets.NEXT_PUBLIC_S3_IMAGE_UPLOAD_BUCKET_NAME }}
          NEXT_PUBLIC_S3_IMAGE_UPLOAD_REGION: ${{ secrets.NEXT_PUBLIC_S3_IMAGE_UPLOAD_REGION }}
          NEXT_PUBLIC_S3_IMAGE_UPLOAD_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_S3_IMAGE_UPLOAD_ACCESS_KEY }}
          NEXT_PUBLIC_S3_IMAGE_UPLOAD_SECRET_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_S3_IMAGE_UPLOAD_SECRET_ACCESS_KEY }}
